#!/bin/bash
if [ "$1" == "" ]; then 
	TAG=2023.05
	CID=da19c18af2d531b63b6d54f02dc2f16785756e66
else
	TAG=$1
fi

cd `dirname $0`

BRDIR=buildroot-${TAG}

cd `dirname $0`
cd ..

if [ -d $BRDIR ]; then
	echo "Saving current buildroot"
	rm -rf $BRDIR.bak
	mv $BRDIR $BRDIR.bak
fi

echo "Checking out buildroot tag ${TAG} from Github"
git clone -v git://git.buildroot.net/buildroot $BRDIR

echo "Checking out a known-good release"
pushd $BRDIR
if [ "$CID" != "" ]; then
	git checkout $CID
else
	git checkout $TAG
fi
popd


echo "Symlinking to buildroot-pbos"
rm buildroot-pbos
ln -s $BRDIR buildroot-pbos

